# font_family ProFont IIx Nerd Font Mono
# font_family FiraCode Nerd Font
font_family JetBrainsMono Nerd Font
# font_family Google Sans Code NF
font_size 11
cursor_shape beam
cursor_blink_interval -1
cursor_trail 100
remember_window_size no
hide_window_decorations yes
background_opacity 0.6
scrollback_lines 2000
enable_audio_bell no
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
copy_on_select clipboard
window_padding_width 12 20 12 20
scrollbar never
mouse_hide_wait 3.0
allow_remote_control yes
confirm_os_window_close 0
notify_on_cmd_finish unfocused
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1

include themes/noctalia.conf
