vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
hwdec=vaapi
target-colorspace-hint=yes
target-colorspace-hint-mode=source
video-sync=display-resample
interpolation=yes
tscale=oversample
scale=spline36
dscale=mitchell
cscale=spline36
dither-depth=auto
dither=fruit
tone-mapping=mobius
tone-mapping-param=0.3
hdr-compute-peak=yes
deband=yes
deband-iterations=4
deband-threshold=48
deband-range=16
deband-grain=48
sub-font="Netflix Sans"
sub-bold=yes
sub-font-size=35
sub-shadow-offset=1
sub-color="#FFFFFF"
fullscreen=yes
osc=no
border=no
save-position-on-quit
