color0 #464554
color1 #ffb4ab
color2 #c2c1ff
color3 #c2c1fe
color4 #faabff
color5 #c2c1ff
color6 #c2c1fe
color7 #e4e1ed
color8 #918fa0
color9 #ffb4ab
color10 #c2c1ff
color11 #c2c1fe
color12 #faabff
color13 #c2c1ff
color14 #c2c1fe
color15 #e4e1ed

cursor                #e4e1ed
cursor_text_color     #13131b
background            #13131b
foreground            #e4e1ed
selection_foreground  #c7c4d7
selection_background  #464554
active_border_color   #c2c1ff
inactive_border_color #464554
url_color             #c2c1ff

active_tab_foreground   #1a01a6
active_tab_background   #c2c1ff
inactive_tab_foreground #c7c4d7
inactive_tab_background #464554
cursor_trail_color      #c7c4d7
